apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: postgres-pv-volume
  labels:
    type: local
    app: fullstack-postgres
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain # Retain the PV even after PVC is deleted.
